-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 14:30:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema riwalennrvfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema riwalennrvfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `riwalennrvfood` DEFAULT CHARACTER SET utf8 ;
USE `riwalennrvfood` ;

-- -----------------------------------------------------
-- Table `riwalennrvfood`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`utilisateurs` (
  `id_user` SMALLINT(3) NOT NULL,
  `login` VARCHAR(70) NOT NULL,
  `nom` VARCHAR(70) NOT NULL,
  `prenom` VARCHAR(70) NOT NULL,
  `telephone` INT(10) ZEROFILL UNSIGNED NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`clients` (
  `id_client` SMALLINT(3) NOT NULL,
  `id_user` SMALLINT(3) NOT NULL,
  `rue_client` LONGTEXT NOT NULL,
  `cp_client` INT NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_client`, `id_user`),
  INDEX `fk_clients_utilisateurs1_idx` (`id_user` ASC),
  CONSTRAINT `fk_clients_utilisateurs`
    FOREIGN KEY (`id_user`)
    REFERENCES `riwalennrvfood`.`utilisateurs` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`livreurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`livreurs` (
  `id_livreur` SMALLINT(3) NOT NULL,
  `id_user` SMALLINT(3) NOT NULL,
  `latitude_zone` FLOAT UNSIGNED NULL,
  `longitude_zone` FLOAT UNSIGNED NULL,
  `rayon_zone` INT(10) NULL,
  `latitude_livreur` FLOAT UNSIGNED NULL,
  `longitude_livreur` FLOAT UNSIGNED NULL,
  PRIMARY KEY (`id_livreur`, `id_user`),
  INDEX `fk_livreurs_utilisateurs1_idx` (`id_user` ASC),
  CONSTRAINT `fk_livreurs_utilisateurs`
    FOREIGN KEY (`id_user`)
    REFERENCES `riwalennrvfood`.`utilisateurs` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`commandes` (
  `id_commande` SMALLINT(3) NOT NULL,
  `id_client` SMALLINT(3) NOT NULL,
  `id_livreur` SMALLINT(3) NOT NULL,
  `statut_commande` VARCHAR(70) NOT NULL,
  `total_commande` INT NOT NULL,
  `heure_commande` TIME(3) NULL,
  `heure_livraison` TIME(3) NULL,
  `rue_commande` LONGTEXT NULL,
  `cp_commande` INT NULL,
  `ville_commande` VARCHAR(255) NULL,
  PRIMARY KEY (`id_commande`, `id_client`, `id_livreur`),
  INDEX `fk_commandes_clients1_idx` (`id_client` ASC),
  INDEX `fk_commandes_livreurs1_idx` (`id_livreur` ASC),
  CONSTRAINT `fk_commandes_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `riwalennrvfood`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commandes_livreurs1`
    FOREIGN KEY (`id_livreur`)
    REFERENCES `riwalennrvfood`.`livreurs` (`id_livreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`produits` (
  `id_produit` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `nom_produit` VARCHAR(70) NOT NULL,
  `description_produit` LONGTEXT NOT NULL,
  `categorie_produit` VARCHAR(45) NOT NULL,
  `prix_produit` DECIMAL(8) NOT NULL,
  PRIMARY KEY (`id_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`ligne_commande` (
  `id_ligne_commande` SMALLINT(3) NOT NULL,
  `id_produit` SMALLINT(3) NOT NULL,
  `id_commande` SMALLINT(3) NOT NULL,
  `quantité` INT(10) NOT NULL,
  PRIMARY KEY (`id_ligne_commande`, `id_produit`, `id_commande`),
  INDEX `fk_ligne_commande_produits1_idx` (`id_produit` ASC),
  INDEX `fk_ligne_commande_commandes1_idx` (`id_commande` ASC),
  CONSTRAINT `fk_ligne_commande_produits1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `riwalennrvfood`.`produits` (`id_produit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ligne_commande_commandes1`
    FOREIGN KEY (`id_commande`)
    REFERENCES `riwalennrvfood`.`commandes` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`stock_livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`stock_livreur` (
  `id_stock_livreur` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `id_produit` SMALLINT(3) NOT NULL,
  `id_livreur` SMALLINT(3) NOT NULL,
  `quantité` INT(10) NOT NULL,
  PRIMARY KEY (`id_stock_livreur`, `id_produit`, `id_livreur`),
  INDEX `fk_stock_livreur_livreurs1_idx` (`id_livreur` ASC),
  INDEX `fk_stock_livreur_produits1_idx` (`id_produit` ASC),
  CONSTRAINT `fk_stock_livreur_livreurs1`
    FOREIGN KEY (`id_livreur`)
    REFERENCES `riwalennrvfood`.`livreurs` (`id_livreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_livreur_produits1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `riwalennrvfood`.`produits` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`carte_bancaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`carte_bancaire` (
  `id_cb` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `id_client` SMALLINT(3) NOT NULL,
  `numero_cb` INT ZEROFILL NULL,
  `expiration_cb` DATE NULL,
  `nom_client` VARCHAR(70) NULL,
  PRIMARY KEY (`id_cb`, `id_client`),
  INDEX `fk_carte_bancaire_clients1_idx` (`id_client` ASC),
  CONSTRAINT `fk_carte_bancaire_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `riwalennrvfood`.`clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`phpmyAdmin OVH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`phpmyAdmin OVH` (
  `login : ` VARCHAR(75) NULL,
  `pass : ` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `riwalennrvfood`.`plat_jour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riwalennrvfood`.`plat_jour` (
  `id_plat_jour` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `id_produit` SMALLINT(3) NOT NULL,
  `date_pj` DATE NULL,
  PRIMARY KEY (`id_plat_jour`, `id_produit`),
  INDEX `fk_plat_jour_produits1_idx` (`id_produit` ASC),
  CONSTRAINT `fk_plat_jour_produits1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `riwalennrvfood`.`produits` (`id_produit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
